#cargo-features = ["once_cell"]

[package]
name = "terraform-provider-cmd"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.tf-provider]
path = "libs/tf-provider"

[dependencies.rusftp]
path = "libs/rusftp"

[dependencies]
async-process = "1.6"
futures = "0.3"
futures-core = "0.3"
futures-util = "0.3"
tokio = { version = "1.0", features = [
    "rt-multi-thread",
    "macros",
    "sync",
    "time",
    "fs",
] }
tokio-stream = { version = "0.1.11", features = ["sync", "net"] }
tokio-util = "0.7"

serde = { version = "1.0", features = ["derive"] }
rand = "0.8"
russh = "0.37"
russh-keys = "0.37"

async-trait = "0.1"
anyhow = "1"
rcgen = "0.10"
base64 = "0.21"
time = "0.3"
rust-crypto = "0.2"
bytes = "1.4"
