on:
  push:
    branches: [ "**" ]

name: Test

jobs:
  build-and-release:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          target: x86_64-unknown-linux-musl
      - uses: Swatinem/rust-cache@v2.2.1
        with:
          shared-key: "cmdrs-build-${{ runner.os }}"
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --target x86_64-unknown-linux-musl --release
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: test
          args: --target x86_64-unknown-linux-musl --release
